name: Test

on: push

jobs:
  test-theme:
    name: Test theme
    runs-on: ubuntu-18.04
    steps:
    - name: Create demo site
      run: php cecil.phar new:site demo
      
    - uses: actions/checkout@master
      with:
        path: 'demo/themes/garth'
    
    - name: Add theme
      run: echo -e "theme:\n  - garth" >> demo/config.yml

    - name: Build demo
      run: |
        curl -sSOL https://cecil.app/cecil.phar
        php cecil.phar build -vv demo
