name: Test

on: push

jobs:
  test-theme:
    name: Test theme
    runs-on: ubuntu-18.04
    steps:
    - name: Download Cecil
      run: curl -sSOL https://cecil.app/cecil.phar

    - name: Create demo site
      run: php cecil.phar new:site demo

    - uses: actions/checkout@master
      with:
        path: 'demo/themes/garth'

    - name: Add theme
      run: |
        echo -e "theme:\n  - garth" >> demo/config.yml
        cat demo/config.yml

    - name: Change baseurl
      run: export CECIL_BASEURL="https://cecilapp.github.io/theme-garth/"

    - name: Build demo
      run: php cecil.phar build -vv demo

    - name: Deploy
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: arnaud@ligny.org
        build_dir: demo/_site
