name: Test

on: push

jobs:
  test-theme:
    name: Test theme
    runs-on: ubuntu-18.04
    steps:
    - name: Download Cecil
      run: curl -sSOL https://cecil.app/cecil.phar

    - uses: actions/checkout@master
      with:
        path: 'themes/garth'

    - name: Create demo
      run: php cecil.phar new:site demo
    
    - name: Add theme
      run: echo -e "theme:\n  - garth" >> demo/config.yml

    - name: Build demo
      run: php cecil.phar build -vv demo
